### ISSUE TITLE
Luke Degnan - 3.28.16

### ISSUE THREAD

**Issue by ldegnan** [Adamor/FEWD3.28#1]
https://github.com/ldegnan/FEWD328_LUKE/commit/e21abfd294742a8a15bd6d65afe6ef77749c4606

Comfort: 5 (except for GitHub)
Completeness: 5
Win/Challenges: GitHub is a tad confusing

**Comment by heyyy-sebastian** [comment]
GitHub is weird at first -- saving things to repositories ends up being muscle memory, but right now the most important thing to know is that we use GitHub to save our code -- it's important to have access to our code history/all the different versions of it in case something breaks later on, so we can see what we added over time & then tracking the different versions helps identify where the bug stems from.

(https://guides.github.com/introduction/getting-your-project-on-github/#desktop)
