### ISSUE TITLE
William Wilcox - Thursday April 7

### ISSUE THREAD

**Issue by wilcoxwc** [Adamor/FEWD3.28#12]
Write Section: CSS Assignment Choice 2
Link to assignment: https://github.com/wilcoxwc/FEWD328_WilliamWilcox/commit/428b34584f4b6a45b5f4d864334e7d9e6e677bec

Comfort: 4
Completeness: 3
Wins/Challenges: I had a lot of trouble with placing the image where it needs to be. Full disclosure, I thought it was my p and body CSS, which I reviewed and used the solution code for after trying different fixes but still didn't fix my issue.

Other comments: Probably the biggest lessoned learned here was managing time. I dedicated about 3-4 hours over the weekend to this, which I now know I need to dedicate a full day. The weekdays are completely packed, so the weekend is the only time I can really focus. I was able to debug the majority of my problems, however when I dedicate more time on the next go around I feel like I'll be able to make the assignment more succinct.

**Comment by heyyy-sebastian** [comment]
Hey Will -

This is a solid start! I think you're most of the way there, you'd just have a few styling updates to make and you'd be all set. For image positioning, it seems like almost everyone has had some trouble with that. Hopefully covering floats in class last week helped clarify how to position images with the text flowing around it, but here's a short how-to as another good reference:  https://css-tricks.com/all-about-floats/

Here are some other things to think about:
- You want to avoid mixing inline styling with an external style sheet. It's cleaner and easier to keep track of all your styling rules if you put them in one place - your css file; I would move the <p> tag styling you have set on your Resume page into your css file and use a class to style these lines so you don't repeat lines of code.
- For styling updates, I would look at the mock-up again and see what styling adjustments need to be made. When you're building your own projects, styling is totally up to you, but if you ever work as a web designer, clients will definitely get nit-picky about the details. So I'd take a look at the colors of the dividing lines, the colors for the links for the About Me/Resume/footer, the font-weight on the schools in the education section and the font-style of Wendy's name on the page.

In terms of HTML, your structure looks great. You're using the right tags and it's well organized. You're the only person so far who's commented their code, so keep that up! Good job! 👍
