### ISSUE TITLE
FEWD3.28 Luke Degnan - Week 2 Homework

### ISSUE THREAD

**Issue by ldegnan** [Adamor/FEWD3.28#23]
https://github.com/ldegnan/FEWD328_LUKE/commit/7030b1a1de3bc4377b3eaa68af33c4033c84700b

Comfort: 4
Completeness: 4.2

Challenges. It took me a little bit to get started with setting up the various areas, but after I figured it out it went pretty smoothly.

**Comment by heyyy-sebastian** [comment]
Hi Luke -

This is fantastic! Probably the cleanest code that I've seen for this assignment so far. The way you use id's with the container class is excellent. The only feedback I have is that overall the font could be a little bigger, but that's it.

Thanks for making this so easy to look at!!!! :100: :tada:
