### ISSUE TITLE
Michelle Hsu Homework 2

### ISSUE THREAD

**Issue by michellehsu** [Adamor/FEWD3.28#25]
Link to assignment: https://github.com/michellehsu/FEWD0328_michelle/commit/b557fd2f4ad752eb2d34c623f182f255b33611dd

Comfort: 4
Completeness: 5
Wins/Challenges: still trying to figure out when to use normalize or reset.

**Comment by heyyy-sebastian** [comment]
Hi Michelle -

This looks really good!!! You've done an excellent job.

The only feedback I have is that you could refactor some of your css in shorthand.  I know we haven't talked about this a whole lot, but for example, if you find yourself writing something like `font-size: 20px;` more than once, chances are you can refactor this. You can apply styling to a specific element, then specify additional styling for multiple elements later on, and that first element will still retain the initial styles. That probably makes no sense to read, but here's what I mean: on lines 73-84 of your css file, you have `font-size:36px;` and `color: #fff;` twice. This can be refactored as:

header h2{
  font-weight: 600;
  text-align: center;
  margin: 120px 0 100px 0;
}

header .logo, header h2{
  color: #fff;
  font-weight: 800;
  font-size: 36px;
} 

So h2 has its own styles, then gets an additional style when it's declared in the group of elements, but still retains its other characteristics.

For normalize vs. reset -- they're more or less two different css files that will reset some of the browsers pre-set styling in different ways: one resets css rules, while the other one (normalize) tries to take into the preset styling rules so they render consistently. Personally I work a lot with resets, but there's more about it here: http://stackoverflow.com/questions/6887336/what-is-the-difference-between-normalize-css-and-reset-css

Great work! :100:
