### ISSUE TITLE
Gabi Zandi - 3.28.17

### ISSUE THREAD

**Issue by gzandi** [Adamor/FEWD3.28#3]
Title Section: Gabi Zandi- Class Day 1
Write Section: 
Link to assignment: https://github.com/Adamor/FEWD3.28/issues

Comfort: 4
Completeness: 5
Wins/Challenges: HTML 5, CSS 3, GIT 2

**Comment by heyyy-sebastian** [comment]
Looks good! 👍 

probably just a copy/paste thing, but your assignment link is tied to your repository: (https://github.com/gzandi/FEWD328_GABI/commit/4929f7911d3cc9db7e2a7c33d36764210e642bd1)
