### ISSUE TITLE
William Wilcox - Week 2 Assigment

### ISSUE THREAD

**Issue by wilcoxwc** [Adamor/FEWD3.28#31]
Comfort: 3.5
Completeness: 4.5

Wins: I am starting to understand the semantics of CSS. I am seeing how structurally things cascade with different changes to selectors.

Challenges: Had trouble getting the FB image to show up and the footer to take on the black background. It is also still taking me a while to debug floating problems.
[Assignment.zip](https://github.com/Adamor/FEWD3.28/files/924598/Assignment.zip)

**Comment by heyyy-sebastian** [comment]
Marking this as complete but will come back to it if I have time!
