### ISSUE TITLE
Jihyun Song - FEWD3.28 -  Week 3 homework

### ISSUE THREAD

**Issue by Jihyunsong0106** [Adamor/FEWD3.28#37]
Here is the week 3 homework.

https://github.com/Jihyunsam143/FEWD328_jihyun/commit/6429349154096d24f774765eff607fb32a69f228

**Comment by heyyy-sebastian** [comment]
Hi Jihyun,

This is excellent! This looks very nice and polished. Your HTML is organized well and the elements/classes on the page are semantic. I would recommend adding comments to denote different sections so someone else could quickly read through it and see the `<!--nav bar-->` or `<!--main content-->` or `<!--sidebar content-->` in your html.

Your CSS looks good as well, but there are a few places you can refactor it. For example, on lines 312-315 and 328-331, you apply the same styles to the hover state of .footer-icon-1 and .footer-icon-2. You can combine these rules to be written as:

```
.footer-icon-1:hover, .footer-icon-2:hover{
/*styles go here*/
}
```
There are a few places you could use this method, so it's just something to keep in mind while you're writing your css.

This is great! Keep up the good work. :100:
