### ISSUE TITLE
Christine Purdy (Week 3)

### ISSUE THREAD

**Issue by czpurdy** [Adamor/FEWD3.28#39]
https://github.com/czpurdy/FEWD328_CHRISTINE/commit/066b8c14b5d179ad23bf97abd71a843bac85ce19 (replaced the link because I didn't notice I broke the sign-up button)

Comfort: 4
Completeness: 5

Wins: I have a better understanding of how to create column layouts, and I think my product looks pretty close to the original. I also tried to use fewer classes and take Hailey's comments from my last assignment into consideration (although I didn't have an opportunity to dedicate as much time as I would've liked).

Challenges: I struggled a lot with the nav and with the anchor tags in general. I was having trouble limiting the clickable portion of the "read only" link to the text--instead the entire area is clickable. I also don't really understand how to properly use the reset and clear fixes. I often forget about them until I'm pretty much finished with the assignment, and I'm afraid I've missed something by not using them. I'll ask more about this during office hours (and maybe a little bit more about flexbox, as I think it took a little longer than it should have!).

**Comment by heyyy-sebastian** [comment]
NICE TRY with the Rick Roll but I can tell that your anchor tags are actually limited to the Read More text that they're wrapped around so I'm not even going to click on that YouTube link. 

Anyway. This looks really good! I just have a few minor things you can adjust:
- Overall the font could be a little bit bigger
- I would increase the margin and add a little bit of padding between the two columns so there's a bit more of a gutter between them
- I think your nav links are horizontally aligned, but it's possible it's an optical illusion from the white/large text of the Relaxr title in comparison with the smaller/yellow text, if that makes sense
- You can shorten some of your styling rules in your css rules. On lines 181-182 of your css file, you set `padding-top: 20px; padding-bottom: 20px;` but you can also write margin/padding as `padding: [top and bottom] [left and right];` so it reads as `padding: 20px 0px;` There are a few places you can update this in your css, or combine your padding/margin rules into one line (take a look at lines 155-156).
 
In response to your question about clearfix, I've used this mainly when I've been trying to get an element pushed down farther on the page and it _just won't clear_ the other element next to it and there's an overlap I don't want. Sometimes, depending on your set up, you just don't end up needing it. Here is a more in-depth explanation: http://stackoverflow.com/questions/8554043/what-is-a-clearfix

Great job! Keep up the good work 🎊
