### ISSUE TITLE
home work week3

### ISSUE THREAD

**Issue by steven0633** [Adamor/FEWD3.28#40]
https://github.com/steven0633/FEWD328_STEVEN/commit/8dc45db256dfb6c7f851328e0392407b9802f693

**Comment by heyyy-sebastian** [comment]
Hi Steven -

This looks great! Awesome job incorporating the keyframes into the navbar. The size of your fonts and the spacing is great, I would just add a little extra margin/padding to the edges of your main content container so the page has a wider margin and the text isn't sitting so close to the edge of the page. Overall the layout is nicely done. Your html is commented very well -- that looks excellent.

To align your links on the navbar with the title, I would look at the display rules that are set on the h1. By default, h1 tags are `display: block;` so they take up the full width of whatever container they're in. That means your Relaxr title is pushing the links down to the next line. Try setting the Relaxr title to `display: inline-block;` and see what happens.

I've been messing around with the L in your first paragraph and I honestly have no idea why applying `float:left` is putting it in a different position than the one on the second paragraph. Everything I've tried so far doesn't work....I'm stumped, honestly, I'll probably ask Arthur about it.

Other than that, your css looks great, I would just try to rewrite some of the rules in shorthand. So for rules like padding/margin, you can rewrite them as `padding: [top] [left] [bottom] [right];` or `padding: [top and bottom] [left and right];` or even `padding: [top][left and right][bottom];`. So your margin rule on lines 25-28 can actually be rewritten as `margin: 0 20px 0 320px;`

Awesome work! :tada:
