### ISSUE TITLE
Yanina Tsutieva-Assignment #3

### ISSUE THREAD

**Issue by yaninaTev** [Adamor/FEWD3.28#42]
Link to assignment: https://github.com/yanatev/FEWD328_Yanina/commit/43a6fae4b9bc93215a85867709b41c8d2e508c83
Comfort-3
Completeness-2
wins/challenges-Margins/ putting css together and time management/
Comments-Sorry for sending in this assignment so late.

**Comment by heyyy-sebastian** [comment]
closing this for now so i can give you feedback on the other submission!
