### ISSUE TITLE
Homework Week 5 - Luke Degnan

### ISSUE THREAD

**Issue by ldegnan** [Adamor/FEWD3.28#48]
https://github.com/ldegnan/FEWD328_LUKE/commit/f875299953279a71c9ac2e14fcff27eca7984cf1

Comfort: 3
Completeness: 5
Challenges: It always takes me a little bit to figure out how to do stuff. I know what I want to do, but I always have to keep checking or looking things up. That seems normal I guess.
Comments: Commit also includes the optional homework, which was unintentional as I did not complete it.

**Comment by heyyy-sebastian** [comment]
Hi Luke -

This is the cleanest code I've seen so far - really nice work! It's normal to keep checking things/look things up. Understanding how you conceptually want to write a program and then looking up the concrete methods for it is a solid approach to good programming. There's too much to know to be able to memorize the whole jQuery library and write programs from memory. Even the best programmers google their way out of their problems.

The way you've set up your code is modular, which is great, meaning your behavior is encapsulated in a function that can be called/executed by other functions. This type of code also scales well. 

The one piece of feedback I have about your set up is that you want to wrap _all_ of your js code in the document ready function. This is typically the wrapper function for all the jQuery code you write. When you put all your code inside this function, it helps prevent load errors. So to get the MakeItHappen function execute when the document ready, your code would be set up like this:

```
$(document).ready(function(){
//ALL your code goes here

MakeItHappen();
});
```

Adding the () after the variable when the variable is a function _invokes_ the function when it's not being passed to another function as a parameter. So if you assign a function to a variable, you can get it to run/invoke it at anytime by just saying `variableName();`

Great job! 🎊
