### ISSUE TITLE
Yuliya Kandratsyeva - week 5 homework

### ISSUE THREAD

**Issue by heyitsyuliya** [Adamor/FEWD3.28#49]
Link to the assignment: https://github.com/yuliyakndr/FEWD328_yuliya/tree/master/week3
Comfort: 4
Completeness: 4

I think I have good understanding on how jQuery works, however there's on problem I couldn't solve.
As you can see in the code, I have two functions being called for 3 different elements that are sharing the same class (had no luck targeting specific IDs, jQuery somehow would pick the wrong ones). Once I click on one element, functions will be executed for the rest of the elements.
I've tried applying same function as described here: http://stackoverflow.com/questions/30518257/jquery-how-do-i-target-the-clicked-element-when-they-all-share-the-same-css-cla

but it never worked 👎

**Comment by heyyy-sebastian** [comment]
:tada: :tada: :tada: this is great!

I'm glad you were able to get the paragraphs to slide up/down independently of each other. That generally seems to be a sticking point for most students for this assignment. `event.target` is a useful thing to learn/get comfortable with. 

The other way people would do this would be to add an "active" class to _this_ (or the target element) to reset the display, and then .removeClass() when you need to hide the content again.

The only thing this is missing is the ability to show content when Learn More is clicked on the aside. I think you just need to add an id to the anchor tag so it will work the same way as your paragraph expansion.

Good job! I'm glad you could pick another dev's brain at work. Another pair of eyes is always helpful. 🤓
