### ISSUE TITLE
FEWD3.28 - Week5-jihyun-song-jquary-homework

### ISSUE THREAD

**Issue by Jihyunsong0106** [Adamor/FEWD3.28#51]
Here is the homework due today!

https://github.com/Jihyunsam143/FEWD328_jihyun/tree/master/week6/relaxr_blog

Thanks,
Jihyun

**Comment by heyyy-sebastian** [comment]
Hi Jihyun -

This works well! You've done a very good job of keeping your code succinct. You've set up your file correctly with the document ready function and the "More" button shows more text. 

I just have two points for feedback:
- To prevent the page from jumping back up to the top when you click the "more button, I would add the prevent default function in your `.click()` method. You can read more about it here: https://api.jquery.com/event.preventdefault/ but basically if you add a method like this:
```
$("a").click(function(event) {
     event.preventDefault(); 
//more code here
      });
```
within your click method that uses toggleClass, it will keep the page from jumping up to the top.

- One of the prompts for the homework was to have text appear when a user clicks the "Learn More" button on the sidebar -- this is very similar to the function you've already written

Overall good job! 👍
