### ISSUE TITLE
Gabrielle Zandi_FEWD328_Homework 6

### ISSUE THREAD

**Issue by gzandi** [Adamor/FEWD3.28#54]
https://github.com/gzandi/FEWD328_GABI/commit/cf7b5596b6fad824f434057f56b694915a99a6d9

Comfort: 4
Completeness: 4

Wins: I was able to complete the technical requirements and felt like I got a much better understanding of responsive design and media queries. 

Challenges: Less of a challenge, but I wish I had taken some more time with this assignment to: 1. change the nav to a mobile hamburger nav, 2. Update the overall page layout to be aligned with the breakpoints (for example, the sidebar stacks under the main blog section before hitting 768, it would be good to have that happen together), 3. Would have switched out the ad for a smaller mobile ad unit (I just adjusted the height to reflect this) and 4. Would have perfected the margins at each breakpoint, for some reason in the blog they kept getting off and weren't aligned.

(But I was able to do this while at my conference in Utah, so yay!)

**Comment by heyyy-sebastian** [comment]
Hey Gabi -

This looks good! Personally I'm not a huge fan of hamburger menus (the general critique being that it's more clicks to get to the content, and therefore probably more clicks to get to the user action you want/user conversion), so in theory it's a good thing to know how to do, but not essential to good responsive design.

Your media queries are all excellent, I would just look at how you can use short-hand for some of your margin rules and think about adding more padding around the text on smaller screensizes so there's more space between the content and the edge of the screen (the font could be a little bit bigger on the blog page at the smallest breakpoint -- if you think about reading articles on your phone and stuff, the text stays fairly large).

w/r/t your other to-dos for this assignment, you could convert the width of your blogroll/sidebar from ems into a percentage (60%/40%), which might scale better. No worries about the adunit, but looking at your margins, they seem to be aligned for me when I resize the window.

Great job! 🎊
