### ISSUE TITLE
hw5

### ISSUE THREAD

**Issue by steven0633** [Adamor/FEWD3.28#55]
https://github.com/steven0633/FEWD328_STEVEN/commit/f022f73235222e673f9612c0002c593523ccc3d0

hi so im having a little problem making my js to work with my html it work once but i started moving things lol and cant figure out what is that i move

**Comment by steven0633** [comment]
so i just figure it out i need to put one more "}):" at the end of the page and will work

**Comment by steven0633** [comment]
}); lol

**Comment by heyyy-sebastian** [comment]
Hey Steven -

Great job! I'm glad you figured out that you needed to add a closing bracket -- syntax errors are one of the main reasons things go wrong/don't work. Your code looks good! It's succinct and it works well. Awesome work 💯
