### ISSUE TITLE
week 6 hw: responsive Relaxr

### ISSUE THREAD

**Issue by michellehsu** [Adamor/FEWD3.28#63]
https://github.com/michellehsu/FEWD0328_michelle/tree/master/week6/homework/relaxr_responsive
Comfort: 3
Completeness: 4

wins: I like how it turns out in terms of layouts in different screen sizes by using media queries. I added margins so it looks better!

challenges: the hamburger menu is challenging.  I wasn't able to select DOM element in Javascrip to write the slideDown function, because the hamburger menu is defined  <nav id="menu">, and not able to use getElementById. The reason to put an #id on <nav> tag is because the <li> was conflicting with the category list in blog page.

**Comment by heyyy-sebastian** [comment]
Hi Michelle -

Your CSS looks great! As does the layout. There are a few places where you could write the styling rules in shorthand, but you'll probably be able to spot them if you look at this again.

For the JS portion, I would recommend using jQuery. I don't know if this is just how the files were downloaded on my end, but the compiler doesn't recognize where your js file is located. It's one level above where it's currently looking, so if you write it as `<script src="/js/main.js"></script>` the / at the beginning will tell your program to look one folder up for the JS folder. If this hasn't been an issue for you, then it's just the way the files downloaded for me and you don't have to worry about any of this.

I would add jQuery either as a minified file to your JS folder or as a link to the library on the web to this project. If you add the jQuery script tag before your main.js file, you should be able to use jQuery, which has a `.slideDown` method you can use when you select the `$('#nav-id')` on the page, or you can use the `.addClass()` method, which would achieve the same thing that you're trying to to with vanilla JS.

Good work! 💯
