### ISSUE TITLE
hw6

### ISSUE THREAD

**Issue by steven0633** [Adamor/FEWD3.28#68]
https://github.com/steven0633/FEWD328_STEVEN/commit/ff8e24d758ed7f5dc3b8b4a8c087af947a922f1d
having some difficulty with the js , really didnt have much time to put into it but show be good

**Comment by heyyy-sebastian** [comment]
Hey Steven -

This looks really good! For styling, I would override the default margin on the body tag so it's set to 0, otherwise you should be good to go.

For the JS, it looks like you're using vanilla JS, and this might be easier with jQuery if end up looking at this again.

Great work! :tada:
