### ISSUE TITLE
 Gabi Final Project Draft for Review 

### ISSUE THREAD

**Issue by gzandi** [Adamor/FEWD3.28#69]
Hi Halie and Arthur, 

I've been working on my final project all weekend and ran into the following issues. Would either of you be able to help me with the following? Do you have office hours tomorrow? 

1. Overlay on carousel images (not working anymore, was working before I put in the slick carousel and now I can't get it to work at all) 
2. Extra top/bottom margin on the About Me section due to flexbox (how can I get rid of this? When I take out margin: auto, then it goes away, but the image becomes huge/distorted and the text floats up) 
3. Responsive Navigation (not working, sometimes it will turn into a hamburger, but I can't get it to open and stay on the top right) 
4. Arrows or swipe to slide for carousel (for some reason I can't get either of these to work, I tried arrows and got them to show up for a brief moment (in the awk mystery margin), and could never get swipe to slide to work at all) 
5. Mystery right side margin (sometimes this mystery 10ish pixel margin appears on the right side of the page)
6. Design/interaction ideas for the My Maps section( it's so boring now)

See here: https://github.com/gzandi/FEWD328_GABI/commit/1618df50bfec26c9acc34ce4e7bbb129d3f64f80

Thank you in advance!
Gabi

**Comment by heyyy-sebastian** [comment]
We did a pull request for this! Yay! obviously hmu if you have any more questions
