### ISSUE TITLE
Jihyun Song - Final Project Revised

### ISSUE THREAD

**Issue by Jihyunsong0106** [Adamor/FEWD3.28#74]
Hi!

Here is the revised link for Jihyun Song's final project.
Please, use this for final.

https://github.com/Jihyunsam143/FEWD328_jihyun/commit/c446d4e6cc3c87e530dcd82a811b10e573eafe32

http://design-prod-watchae.s3.amazonaws.com/prototypes/ga-fewd-3-28/cafe-manna-revised/index.html

Thanks,
Jihyun

**Comment by heyyy-sebastian** [comment]
I left you some feedback on the original issue you added! Let me know if you have questions :)

**Comment by Jihyunsong0106** [comment]
Okay! Thank you!
